name: Copy Ironweb-Research's Main-Repo Primary Components to Sub-Repos

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout receiving repo we_are folder
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUSH_COMPONENTS_TOKEN }}
          # path: temp_components
          repository: ironweb-research/we_are
          sparse-checkout: |
            src/app/_components
          sparse-checkout-cone-mode: false
      - name: Verify PWD receiving repo we_are folder
        id: pwd-we_are
        run: |
          echo "pwd-we_are directory---->: $(pwd)"
          echo "git remote -v  can be run?"
          /usr/bin/git remote -v
          echo "git status               ---->: $(/usr/bin/git status)"
  
      - name: Checkout source repo iw_homwpage folder
        uses: actions/checkout@v4
        with:
          path: temp_components
          sparse-checkout: |
            src/app/_components

        # - name: Move blog post to correct level
      - name: Verify PWD source repo iw_homwpage folder
        id: pwd-iw_homepage
        run: |
          echo "pwd-iw_homepage directory---->: $(pwd)"
          echo "git remote -v  can be run?"
          /usr/bin/git remote -v
          echo "git status               ---->: $(/usr/bin/git status)"
        #   id: move_blog_post

