name: Deploy Next.js site to Ironweb-Research's GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout _component folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            src/app/_components

        # - name: Move blog post to correct level
      - name: Verify PWD 
        id: pwd-iw_homepage
        run: |
          echo "pwd-iw_homepage directory---->: $(pwd)"
          echo "git remote -v  can be run?"
          /usr/bin/git remote -v
        #   id: move_blog_post
      # - name: Checkout receiving repo folder
      #   uses: actions/checkout@v4
      #   with:
      #     token: ${{ secrets.PUSH_COMPONENTS_TOKEN }}
      #     path: temp_components
      #     repository: ironweb-research/we_are
      #     sparse-checkout: |
      #       src/app/_components
      #     sparse-checkout-cone-mode: false

      - name: Change git remote to dumpster
        id: change_git_remote_to_dumpster
        run: |
          echo "change git remote to dumpster"
          /usr/bin/git remote remove origin          
          /usr/bin/git remote add origin https://github.com/ironweb-research/dumpster.git
          
      - name: Upload file
        id: upload_file
        run: |
          echo "Upload file(s)"
          /usr/bin/git add src/app/_components/test.txt
          
          /usr/bin/git commit -m "test upload src/app/_components/test.txt"

          /usr/bin/git push -u origin main --force

      - name: Reset git remote
        id: reset_git_remote
        run: |
          echo "Reset git remote"
          /usr/bin/git remote remove origin
          
          /usr/bin/git remote add origin https://github.com/ironweb-research/ironweb-research.github.io.git



          echo "pwd-we_are      after upload---->: $(pwd)"
          ls -Rlha .
          echo "git remote -v  can be run?"
          /usr/bin/git remote -v
      #   run: |
      #     mv ./_posts/_posts/*.md _posts
      #     rm ./_posts/README.md
      #     find ./_posts -mindepth 1 -depth -type d ! -name "*.md" -exec rm -r {} +
      - name: Verify PWD 
        id: present-working-directory
        run: |
          echo "pwd-we_are      directory---->: $(pwd)"
          echo "Advance check on all contents, incl hidden, are loaded onto present working directory"
          ls -lha
          echo "git remote -v  can be run?"
          /usr/bin/git remote -v
          echo "Advance check on workflow loaded onto ./temp_components"
          ls -Rlha ./temp_components
#          echo "Advance check on blog post loaded onto ./_posts"
#          ls -lha ./_posts
